name: Quality Gate

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    env:
      SHA_FULL: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Add server to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.HOST }} > ~/.ssh/known_hosts

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build and Verify
        if: github.event_name == 'push' || github.event.pull_request.merged == true
        run: |
          chmod +x ./gradlew
          ./gradlew bootJar
          docker build -t ngobrol:${SHA_FULL:0:7} .

      - name: Deploy to Production

        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          
          
          docker tag ngobrol:${SHA_FULL:0:7} ${{ secrets.DOCKER_USERNAME }}/ngobrol-be:latest
          docker tag ngobrol:${SHA_FULL:0:7} ${{ secrets.DOCKER_USERNAME }}/ngobrol-be:${SHA_FULL:0:7}
          docker push ${{ secrets.DOCKER_USERNAME }}/ngobrol-be:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ngobrol-be:${SHA_FULL:0:7}
          
          SSH_TARGET="${{ secrets.USER }}@${{ secrets.HOST }}"
          ssh "$SSH_TARGET" << EOF
            docker pull ${{ secrets.DOCKER_USERNAME }}/ngobrol-be:latest
            cd /opt/ngobrol
            docker-compose down
            docker-compose up -d
            docker image prune -f
          
            echo "🎉 Noiicee!"
          EOF